-- Domain migration dispatcher.
-- Domain schemas are applied by infra/migrations/migrate.sh and CI in lexical order
-- from domains/*/migrations/*.sql. This file intentionally contains no \\ir statements
-- so a migration cannot be executed twice by accident.
