DO $$ DECLARE r record; BEGIN
FOR r IN SELECT unnest(ARRAY['hospital_patients','hospital_staff','hospital_appointments','hospital_encounters','hospital_admissions','hospital_billing','hospital_departments','hospital_wards','hospital_beds','hospital_prescriptions','hospital_lab_orders','hospital_radiology_orders','hospital_insurance_policies','hospital_invoice_items','hospital_payments','hospital_discharge_summaries','hospital_skin_consultations','hospital_skin_treatments','hospital_eecp_programs','hospital_eecp_sessions','hospital_physio_assessments','hospital_physio_sessions','hospital_specialty_clinics','hospital_specialty_appointments','hospital_specialty_billing_packages','hospital_specialty_invoices','hospital_specialty_portal_profiles','school_students','school_teachers','school_classes','school_enrollments','school_attendance','college_students','college_faculty','college_departments','college_courses','college_enrollments','college_attendance','college_fees','college_exams','college_exam_results','hotel_guests','hotel_room_types','hotel_rooms','hotel_bookings','hotel_payments','hotel_housekeeping','realestate_properties','realestate_units','realestate_listings','realestate_leads','realestate_viewings','realestate_offers','realestate_leases','realestate_payments']) table_name LOOP
  EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', r.table_name); EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', r.table_name);
  EXECUTE format('DROP POLICY IF EXISTS tenant_isolation ON %I', r.table_name);
  EXECUTE format('CREATE POLICY tenant_isolation ON %I USING (tenant_id = current_setting(''app.tenant_id'', true)::uuid) WITH CHECK (tenant_id = current_setting(''app.tenant_id'', true)::uuid)', r.table_name);
END LOOP; END $$;
ALTER TABLE platform_audit ENABLE ROW LEVEL SECURITY; ALTER TABLE platform_audit FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON platform_audit;
CREATE POLICY tenant_isolation ON platform_audit USING (tenant_id=current_setting('app.tenant_id',true)::uuid) WITH CHECK (tenant_id=current_setting('app.tenant_id',true)::uuid);
