apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: emtaf
resources:
- ../../base
images:
- name: emtaf-tenant-service
  newName: emtaf-tenant-service
  newTag: dev
- name: emtaf-hospital-service
  newName: emtaf-hospital-service
  newTag: dev
- name: emtaf-school-service
  newName: emtaf-school-service
  newTag: dev
- name: emtaf-college-service
  newName: emtaf-college-service
  newTag: dev
- name: emtaf-hotel-service
  newName: emtaf-hotel-service
  newTag: dev
- name: emtaf-realestate-service
  newName: emtaf-realestate-service
  newTag: dev
- name: emtaf-demo-wireframe
  newName: emtaf-demo-wireframe
  newTag: dev
- name: emtaf-migrations
  newName: emtaf-migrations
  newTag: dev
- name: emtaf-hospital-site
  newName: emtaf-hospital-site
  newTag: dev
- name: emtaf-school-site
  newName: emtaf-school-site
  newTag: dev
- name: emtaf-college-site
  newName: emtaf-college-site
  newTag: dev
- name: emtaf-hotel-site
  newName: emtaf-hotel-site
  newTag: dev
- name: emtaf-realestate-site
  newName: emtaf-realestate-site
  newTag: dev
- name: emtaf-skin-clinic-site
  newName: emtaf-skin-clinic-site
  newTag: dev
- name: emtaf-eecp-clinic-site
  newName: emtaf-eecp-clinic-site
  newTag: dev
- name: emtaf-physiotherapy-site
  newName: emtaf-physiotherapy-site
  newTag: dev
patches:
- path: postgres-secret-patch.yaml
- path: platform-secrets-patch.yaml
