apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: emtaf
stringData:
  password: emtaf-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: emtaf-platform-secrets
  namespace: emtaf
stringData:
  DATABASE_URL: postgresql://emtaf:emtaf-dev@postgres.emtaf.svc.cluster.local:5432/emtaf
  JWT_SECRET: emtaf-dev-jwt-secret
