apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: emtaf
resources:
- namespace.yaml
- config.yaml
- platform-infra.yaml
- security.yaml
- tenant-service.yaml
- hospital-service.yaml
- school-service.yaml
- college-service.yaml
- hotel-service.yaml
- realestate-service.yaml
- demo-wireframe.yaml
- realestate-site.yaml
- hotel-site.yaml
- college-site.yaml
- school-site.yaml
- hospital-site.yaml
- resource-limits.yaml
- observability.yaml
- otel-collector-config.yaml
- migration-job.yaml
- outbox-worker.yaml
- skin-clinic-site.yaml
- eecp-clinic-site.yaml
- physiotherapy-site.yaml
