import { startTelemetry } from '@emtaf/core/dist/telemetry';
import express from 'express'; import cors from 'cors'; import rateLimit from 'express-rate-limit';
import helmet from 'helmet';
import client from 'prom-client';
import { db, audit, idempotent, getIdempotencyKey } from '@emtaf/core';
import { context, permission, error, json } from '@emtaf/core/dist/http';

startTelemetry(process.env.OTEL_SERVICE_NAME||'hospital-service');
const app = express(); app.disable('x-powered-by'); app.set('trust proxy', process.env.TRUST_PROXY||'1'); app.use(cors({origin:(process.env.CORS_ORIGINS||'').split(',').map((v:string)=>v.trim()).filter(Boolean),credentials:true})); app.use(rateLimit({windowMs:Number(process.env.RATE_LIMIT_WINDOW_MS||60000),limit:Number(process.env.RATE_LIMIT_MAX||300),standardHeaders:'draft-7',legacyHeaders:false,skip:(req:any)=>req.path.startsWith('/health')||req.path==='/metrics'}));
app.use(helmet({contentSecurityPolicy:process.env.NODE_ENV==='production'?undefined:false}));
app.use(express.json({limit:'1mb'}));
client.collectDefaultMetrics();

app.get('/health/live',(_,res)=>res.json({status:'ok',service:'hospital-service',version:process.env.SERVICE_VERSION||'1.10.5'}));
app.get('/health/ready',async(_,res)=>{try{await db.query('select 1');res.json({status:'ready'})}catch{res.status(503).json({status:'not-ready'})}});
app.get('/metrics',async(_,res)=>{res.setHeader('Content-Type',client.register.contentType);res.end(await client.register.metrics())});
app.use((req,res,next)=>{if(req.path.startsWith('/health')||req.path==='/metrics')return next();context(req).then(()=>next()).catch(e=>error(res,e))});
const tid=(req:any)=>req.emtaf.tenantId;
const param=(req:any,name:string):string=>{const value=req.params?.[name];return Array.isArray(value)?String(value[0]??''):String(value??'')};
const run=(fn: import('express').RequestHandler): import('express').RequestHandler => (req,res,next)=>Promise.resolve().then(()=>fn(req,res,next)).catch(e=>error(res,e));
const q=(req:any,sql:string,values:any[]=[])=>db.withTenant(tid(req),(c:any)=>c.query(sql,values)) as Promise<any>;

app.get('/api/v1/hospital/me',(req,res)=>json(res,{userId:req.emtaf.userId,tenantId:tid(req),roles:req.emtaf.roles}));

// Dashboard
app.get('/api/v1/hospital/dashboard',run(async(req,res)=>{const [p,a,e,adm,lab,rad,inv]=await Promise.all([
 q(req,"select count(*)::int count from hospital_patients where status='active'"),q(req,"select count(*)::int count from hospital_appointments where status='scheduled' and starts_at>=now()"),q(req,"select count(*)::int count from hospital_encounters where status='open'"),q(req,"select count(*)::int count from hospital_admissions where status='admitted'"),q(req,"select count(*)::int count from hospital_lab_orders where status in ('ordered','in_progress')"),q(req,"select count(*)::int count from hospital_radiology_orders where status in ('ordered','in_progress')"),q(req,"select coalesce(sum(amount),0)::numeric total from hospital_billing where status='unpaid'")
]);json(res,{patients:p.rows[0].count,upcomingAppointments:a.rows[0].count,openEncounters:e.rows[0].count,activeAdmissions:adm.rows[0].count,pendingLabOrders:lab.rows[0].count,pendingRadiologyOrders:rad.rows[0].count,unpaidAmount:inv.rows[0].total})}));

// Patients
app.get('/api/v1/hospital/patients',run(async(req,res)=>{permission('patients:read')(req);const limit=Math.min(Number(req.query.limit)||50,200);const r=await q(req,"select * from hospital_patients where status='active' order by created_at desc limit $1",[limit]);json(res,r.rows)}));
app.post('/api/v1/hospital/patients',run(async(req,res)=>{permission('patients:write')(req);const b=req.body||{};if(!b.mrn||!b.first_name||!b.last_name)return json(res,{error:'mrn, first_name and last_name are required'},400);const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for patient creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_patients(tenant_id,mrn,first_name,last_name,dob,phone,email,user_id) values($1,$2,$3,$4,$5,$6,$7,$8) returning *',[tid(req),b.mrn,b.first_name,b.last_name,b.dob||null,b.phone||null,b.email||null,b.user_id||null]);await c.query('INSERT INTO platform_audit(tenant_id,user_id,action,entity,entity_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[tid(req),req.emtaf.userId,'create','hospital_patient',r.rows[0].id,{mrn:r.rows[0].mrn}]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.get('/api/v1/hospital/patients/:id',run(async(req,res)=>{permission('patients:read')(req);const r=await q(req,"select * from hospital_patients where id=$1 and status='active'",[param(req,'id')]);if(!r.rowCount)return json(res,{error:'Not found'},404);json(res,r.rows[0])}));
app.patch('/api/v1/hospital/patients/:id',run(async(req,res)=>{permission('patients:write')(req);const b=req.body||{};const r=await q(req,"update hospital_patients set first_name=coalesce($2,first_name),last_name=coalesce($3,last_name),dob=coalesce($4,dob),phone=coalesce($5,phone),email=coalesce($6,email),updated_at=now() where id=$1 and status='active' returning *",[param(req,'id'),b.first_name,b.last_name,b.dob,b.phone,b.email]);if(!r.rowCount)return json(res,{error:'Not found'},404);await audit('update',req.emtaf,'hospital_patient',param(req,'id'));json(res,r.rows[0])}));
app.delete('/api/v1/hospital/patients/:id',run(async(req,res)=>{permission('patients:write')(req);const r=await q(req,"update hospital_patients set status='deleted',updated_at=now() where id=$1 and status='active' returning id",[param(req,'id')]);if(!r.rowCount)return json(res,{error:'Not found'},404);await audit('delete',req.emtaf,'hospital_patient',param(req,'id'));json(res,{deleted:true})}));

// Departments / staff
app.get('/api/v1/hospital/departments',run(async(req,res)=>{permission('departments:read')(req);json(res,(await q(req,'select * from hospital_departments where status=\'active\' order by name')).rows)}));
app.post('/api/v1/hospital/departments',run(async(req,res)=>{permission('departments:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for department creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_departments(tenant_id,name,code,head_user_id) values($1,$2,$3,$4) returning *',[tid(req),b.name,b.code||null,b.head_user_id||null]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.patch('/api/v1/hospital/departments/:id',run(async(req,res)=>{permission('departments:write')(req);const b=req.body||{};const r=await q(req,'update hospital_departments set name=coalesce($2,name),code=coalesce($3,code),head_user_id=coalesce($4,head_user_id) where id=$1 returning *',[param(req,'id'),b.name,b.code,b.head_user_id]);if(!r.rowCount)return json(res,{error:'Not found'},404);json(res,r.rows[0])}));
app.get('/api/v1/hospital/staff',run(async(req,res)=>{permission('staff:read')(req);json(res,(await q(req,'select * from hospital_staff where status=\'active\' order by created_at desc')).rows)}));
app.post('/api/v1/hospital/staff',run(async(req,res)=>{permission('staff:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for staff creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_staff(tenant_id,user_id,role,department) values($1,$2,$3,$4) returning *',[tid(req),b.user_id,b.role,b.department||null]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.patch('/api/v1/hospital/staff/:id',run(async(req,res)=>{permission('staff:write')(req);const b=req.body||{};const r=await q(req,'update hospital_staff set role=coalesce($2,role),department=coalesce($3,department),status=coalesce($4,status) where id=$1 returning *',[param(req,'id'),b.role,b.department,b.status]);if(!r.rowCount)return json(res,{error:'Not found'},404);json(res,r.rows[0])}));

// Appointments / encounters
app.get('/api/v1/hospital/patient/me',run(async(req,res)=>{permission('patients:self')(req);const r=await q(req,'select * from hospital_patients where user_id=$1 and status=\'active\'',[req.emtaf.userId]);if(!r.rowCount)return json(res,{error:'Patient profile not linked'},404);json(res,r.rows[0])}));
app.get('/api/v1/hospital/patient/me/prescriptions',run(async(req,res)=>{permission('prescriptions:self')(req);const r=await q(req,'select x.* from hospital_prescriptions x join hospital_patients p on p.id=x.patient_id where p.user_id=$1 order by x.created_at desc',[req.emtaf.userId]);json(res,r.rows)}));
app.get('/api/v1/hospital/patient/me/lab',run(async(req,res)=>{permission('lab:self')(req);const r=await q(req,'select x.* from hospital_lab_orders x join hospital_patients p on p.id=x.patient_id where p.user_id=$1 order by x.ordered_at desc',[req.emtaf.userId]);json(res,r.rows)}));
app.get('/api/v1/hospital/patient/me/radiology',run(async(req,res)=>{permission('radiology:self')(req);const r=await q(req,'select x.* from hospital_radiology_orders x join hospital_patients p on p.id=x.patient_id where p.user_id=$1 order by x.ordered_at desc',[req.emtaf.userId]);json(res,r.rows)}));
app.get('/api/v1/hospital/appointments',run(async(req,res)=>{permission('appointments:manage')(req);const r=await q(req,'select a.*,p.mrn,p.first_name,p.last_name from hospital_appointments a join hospital_patients p on p.id=a.patient_id where a.starts_at>=coalesce($1::timestamptz,now()) order by a.starts_at limit 200',[req.query.from||null]);json(res,r.rows)}));
app.post('/api/v1/hospital/appointments',run(async(req,res)=>{permission('appointments:manage')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for appointment creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_appointments(tenant_id,patient_id,provider_user_id,starts_at,ends_at,reason) values($1,$2,$3,$4,$5,$6) returning *',[tid(req),b.patient_id,b.provider_user_id||null,b.starts_at,b.ends_at,b.reason||null]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.patch('/api/v1/hospital/appointments/:id/cancel',run(async(req,res)=>{permission('appointments:manage')(req);const r=await q(req,"update hospital_appointments set status='cancelled' where id=$1 and status='scheduled' returning *",[param(req,'id')]);if(!r.rowCount)return json(res,{error:'Not found'},404);json(res,r.rows[0])}));
app.post('/api/v1/hospital/encounters',run(async(req,res)=>{permission('clinical:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for encounter creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_encounters(tenant_id,patient_id,provider_user_id,chief_complaint,notes) values($1,$2,$3,$4,$5) returning *',[tid(req),b.patient_id,req.emtaf.userId,b.chief_complaint||null,b.notes||null]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.get('/api/v1/hospital/encounters/:id',run(async(req,res)=>{permission('clinical:read')(req);const r=await q(req,'select * from hospital_encounters where id=$1',[param(req,'id')]);if(!r.rowCount)return json(res,{error:'Not found'},404);json(res,r.rows[0])}));
app.patch('/api/v1/hospital/encounters/:id/close',run(async(req,res)=>{permission('clinical:write')(req);const r=await q(req,"update hospital_encounters set status='closed',closed_at=now(),updated_at=now() where id=$1 and status='open' returning *",[param(req,'id')]);if(!r.rowCount)return json(res,{error:'Not found'},404);json(res,r.rows[0])}));

// Wards / beds
app.get('/api/v1/hospital/wards',run(async(req,res)=>{permission('beds:read')(req);json(res,(await q(req,'select w.*,count(b.id)::int bed_count,count(b.id) filter(where b.status=\'available\')::int available_beds from hospital_wards w left join hospital_beds b on b.ward_id=w.id group by w.id order by w.name')).rows)}));
app.post('/api/v1/hospital/wards',run(async(req,res)=>{permission('beds:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for ward creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_wards(tenant_id,department_id,name,code,capacity) values($1,$2,$3,$4,$5) returning *',[tid(req),b.department_id||null,b.name,b.code||null,Number(b.capacity)||0]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.post('/api/v1/hospital/beds',run(async(req,res)=>{permission('beds:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for bed creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_beds(tenant_id,ward_id,bed_no) values($1,$2,$3) returning *',[tid(req),b.ward_id,b.bed_no]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.get('/api/v1/hospital/beds',run(async(req,res)=>{permission('beds:read')(req);json(res,(await q(req,'select b.*,w.name ward_name,p.mrn,p.first_name,p.last_name from hospital_beds b join hospital_wards w on w.id=b.ward_id left join hospital_patients p on p.id=b.patient_id order by w.name,b.bed_no')).rows)}));
app.post('/api/v1/hospital/beds/:id/assign',run(async(req,res)=>{permission('beds:write')(req);const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for bed assignment',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query("update hospital_beds set patient_id=$2,status='occupied' where id=$1 and status='available' returning *",[param(req,'id'),req.body.patient_id]);if(!r.rowCount)return {statusCode:409,body:{error:'Bed unavailable'}};return {body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.post('/api/v1/hospital/beds/:id/release',run(async(req,res)=>{permission('beds:write')(req);const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for bed release',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query("update hospital_beds set patient_id=null,status='available' where id=$1 returning *",[param(req,'id')]);if(!r.rowCount)return {statusCode:404,body:{error:'Not found'}};return {body:r.rows[0]};});json(res,result.body,result.statusCode)}));

// Admissions / discharge
app.get('/api/v1/hospital/admissions',run(async(req,res)=>{permission('admissions:read')(req);json(res,(await q(req,"select a.*,p.mrn,p.first_name,p.last_name from hospital_admissions a join hospital_patients p on p.id=a.patient_id where a.status='admitted' order by a.admitted_at desc")).rows)}));
app.post('/api/v1/hospital/admissions',run(async(req,res)=>{permission('admissions:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for admission creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_admissions(tenant_id,patient_id,ward,bed_no,notes) values($1,$2,$3,$4,$5) returning *',[tid(req),b.patient_id,b.ward||null,b.bed_no||null,b.notes||null]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.post('/api/v1/hospital/admissions/:id/discharge',run(async(req,res)=>{permission('discharge:write')(req);const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for discharge',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query("update hospital_admissions set status='discharged',discharged_at=now() where id=$1 and status='admitted' returning *",[param(req,'id')]);if(!r.rowCount)return {statusCode:404,body:{error:'Not found'}};return {body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.post('/api/v1/hospital/admissions/:id/discharge-summary',run(async(req,res)=>{permission('discharge:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for discharge summary creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const a=await c.query('select patient_id from hospital_admissions where id=$1',[param(req,'id')]);if(!a.rowCount)return {statusCode:404,body:{error:'Admission not found'}};const r=await c.query('insert into hospital_discharge_summaries(tenant_id,admission_id,patient_id,prepared_by,diagnosis,procedures,medications,follow_up,summary) values($1,$2,$3,$4,$5,$6,$7,$8,$9) on conflict(tenant_id,admission_id) do update set diagnosis=excluded.diagnosis,procedures=excluded.procedures,medications=excluded.medications,follow_up=excluded.follow_up,summary=excluded.summary returning *',[tid(req),param(req,'id'),a.rows[0].patient_id,req.emtaf.userId,b.diagnosis||null,b.procedures||null,b.medications||null,b.follow_up||null,b.summary||null]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));

// Prescriptions
app.get('/api/v1/hospital/prescriptions',run(async(req,res)=>{permission('prescriptions:read')(req);const r=await q(req,'select * from hospital_prescriptions where patient_id=coalesce($1::uuid,patient_id) order by created_at desc limit 200',[req.query.patient_id||null]);json(res,r.rows)}));
app.post('/api/v1/hospital/prescriptions',run(async(req,res)=>{permission('prescriptions:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for prescription creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_prescriptions(tenant_id,patient_id,encounter_id,prescribed_by,medicine,dosage,duration,quantity,instructions) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *',[tid(req),b.patient_id,b.encounter_id||null,req.emtaf.userId,b.medicine,b.dosage||null,b.duration||null,b.quantity||null,b.instructions||null]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.patch('/api/v1/hospital/prescriptions/:id/stop',run(async(req,res)=>{permission('prescriptions:write')(req);const r=await q(req,"update hospital_prescriptions set status='stopped' where id=$1 and status='active' returning *",[param(req,'id')]);if(!r.rowCount)return json(res,{error:'Not found'},404);json(res,r.rows[0])}));

// Laboratory / radiology
app.get('/api/v1/hospital/lab/orders',run(async(req,res)=>{permission('lab:read')(req);json(res,(await q(req,'select * from hospital_lab_orders where patient_id=coalesce($1::uuid,patient_id) order by ordered_at desc limit 200',[req.query.patient_id||null])).rows)}));
app.post('/api/v1/hospital/lab/orders',run(async(req,res)=>{permission('lab:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for lab order creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_lab_orders(tenant_id,patient_id,encounter_id,ordered_by,test_name,priority) values($1,$2,$3,$4,$5,$6) returning *',[tid(req),b.patient_id,b.encounter_id||null,req.emtaf.userId,b.test_name,b.priority||'routine']);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.patch('/api/v1/hospital/lab/orders/:id/result',run(async(req,res)=>{permission('lab:write')(req);const r=await q(req,"update hospital_lab_orders set status='completed',result=$2,completed_at=now() where id=$1 returning *",[param(req,'id'),req.body.result||null]);if(!r.rowCount)return json(res,{error:'Not found'},404);json(res,r.rows[0])}));
app.get('/api/v1/hospital/radiology/orders',run(async(req,res)=>{permission('radiology:read')(req);json(res,(await q(req,'select * from hospital_radiology_orders where patient_id=coalesce($1::uuid,patient_id) order by ordered_at desc limit 200',[req.query.patient_id||null])).rows)}));
app.post('/api/v1/hospital/radiology/orders',run(async(req,res)=>{permission('radiology:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for radiology order creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_radiology_orders(tenant_id,patient_id,encounter_id,ordered_by,study,priority) values($1,$2,$3,$4,$5,$6) returning *',[tid(req),b.patient_id,b.encounter_id||null,req.emtaf.userId,b.study,b.priority||'routine']);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.patch('/api/v1/hospital/radiology/orders/:id/report',run(async(req,res)=>{permission('radiology:write')(req);const r=await q(req,"update hospital_radiology_orders set status='completed',report=$2,completed_at=now() where id=$1 returning *",[param(req,'id'),req.body.report||null]);if(!r.rowCount)return json(res,{error:'Not found'},404);json(res,r.rows[0])}));

// Insurance
app.get('/api/v1/hospital/insurance',run(async(req,res)=>{permission('insurance:read')(req);json(res,(await q(req,'select * from hospital_insurance_policies where patient_id=coalesce($1::uuid,patient_id) order by valid_to desc',[req.query.patient_id||null])).rows)}));
app.post('/api/v1/hospital/insurance',run(async(req,res)=>{permission('insurance:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for insurance policy creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_insurance_policies(tenant_id,patient_id,provider,policy_no,member_no,valid_from,valid_to) values($1,$2,$3,$4,$5,$6,$7) returning *',[tid(req),b.patient_id,b.provider,b.policy_no,b.member_no||null,b.valid_from||null,b.valid_to||null]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));

// Billing / items / payments
app.get('/api/v1/hospital/billing',run(async(req,res)=>{permission('billing:read')(req);json(res,(await q(req,'select b.*,p.mrn,p.first_name,p.last_name,coalesce(sum(i.amount),0)::numeric item_total,coalesce(sum(pm.amount),0)::numeric paid_total from hospital_billing b join hospital_patients p on p.id=b.patient_id left join hospital_invoice_items i on i.invoice_id=b.id left join hospital_payments pm on pm.invoice_id=b.id group by b.id,p.mrn,p.first_name,p.last_name order by b.issued_at desc limit 200')).rows)}));
app.post('/api/v1/hospital/billing',run(async(req,res)=>{permission('billing:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for invoice creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_billing(tenant_id,patient_id,invoice_no,amount) values($1,$2,$3,$4) returning *',[tid(req),b.patient_id,b.invoice_no,b.amount]);await c.query('INSERT INTO platform_audit(tenant_id,user_id,action,entity,entity_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[tid(req),req.emtaf.userId,'create','hospital_billing',r.rows[0].id,{}]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.post('/api/v1/hospital/billing/:id/items',run(async(req,res)=>{permission('billing:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for invoice item creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_invoice_items(tenant_id,invoice_id,description,quantity,unit_price) values($1,$2,$3,$4,$5) returning *',[tid(req),param(req,'id'),b.description,b.quantity||1,b.unit_price]);await c.query('update hospital_billing set amount=(select coalesce(sum(amount),0) from hospital_invoice_items where invoice_id=$1) where id=$1',[param(req,'id')]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.post('/api/v1/hospital/billing/:id/payments',run(async(req,res)=>{permission('billing:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for payment',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_payments(tenant_id,invoice_id,amount,method,reference) values($1,$2,$3,$4,$5) returning *',[tid(req),param(req,'id'),b.amount,b.method,b.reference||null]);await c.query("update hospital_billing set status=case when (select coalesce(sum(amount),0) from hospital_payments where invoice_id=$1)>=(select amount from hospital_billing where id=$1) then 'paid' else 'partial' end,paid_at=case when (select coalesce(sum(amount),0) from hospital_payments where invoice_id=$1)>=(select amount from hospital_billing where id=$1) then now() else paid_at end where id=$1",[param(req,'id')]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));


// Atomic admission + bed allocation workflow (v1.2)
app.post('/api/v1/hospital/admissions/allocate',run(async(req,res)=>{
  permission('admissions:write')(req); permission('beds:write')(req);
  const b=req.body||{}; const key=getIdempotencyKey(req); if(!key)return json(res,{error:'Idempotency-Key header is required for admission allocation',requestId:req.emtaf.requestId},400);
  const result=await idempotent(req,key,async(c:any)=>{
    await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',[`${tid(req)}:${b.bed_id||''}`]);
    const bed=await c.query("select * from hospital_beds where id=$1 for update",[b.bed_id]);
    if(!bed.rowCount || bed.rows[0].status!=='available') throw Object.assign(new Error('Bed unavailable'),{statusCode:409});
    const admission=await c.query('insert into hospital_admissions(tenant_id,patient_id,ward_id,bed_id,ward,bed_no,notes) values($1,$2,$3,$4,$5,$6,$7) returning *',[tid(req),b.patient_id,bed.rows[0].ward_id,bed.rows[0].id,b.ward||null,bed.rows[0].bed_no,b.notes||null]);
    await c.query("update hospital_beds set status='occupied',patient_id=$2 where id=$1",[b.bed_id,b.patient_id]);
    
    return {statusCode:201,body:admission.rows[0]};
  }); json(res,result.body,result.statusCode);
}));

// Specialty clinics: shared hospital patient registry with tenant-scoped clinical workflows.
app.get('/api/v1/hospital/skin/consultations',run(async(req,res)=>{permission('specialty:skin:read')(req);json(res,(await q(req,'select * from hospital_skin_consultations where patient_id=coalesce($1::uuid,patient_id) order by created_at desc limit 200',[req.query.patient_id||null])).rows)}));
app.post('/api/v1/hospital/skin/consultations',run(async(req,res)=>{permission('specialty:skin:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for skin consultation creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_skin_consultations(tenant_id,patient_id,provider_user_id,skin_type,concerns,assessment,diagnosis,allergies,treatment_plan) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *',[tid(req),b.patient_id,b.provider_user_id||req.emtaf.userId,b.skin_type||null,b.concerns||null,b.assessment||null,b.diagnosis||null,b.allergies||null,b.treatment_plan||null]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.patch('/api/v1/hospital/skin/consultations/:id',run(async(req,res)=>{permission('specialty:skin:write')(req);const b=req.body||{};const r=await q(req,'update hospital_skin_consultations set assessment=coalesce($2,assessment),diagnosis=coalesce($3,diagnosis),treatment_plan=coalesce($4,treatment_plan),status=coalesce($5,status),updated_at=now() where id=$1 returning *',[param(req,'id'),b.assessment,b.diagnosis,b.treatment_plan,b.status]);if(!r.rowCount)return json(res,{error:'Not found'},404);json(res,r.rows[0])}));
app.get('/api/v1/hospital/skin/treatments',run(async(req,res)=>{permission('specialty:skin:read')(req);json(res,(await q(req,'select * from hospital_skin_treatments where patient_id=coalesce($1::uuid,patient_id) order by created_at desc limit 200',[req.query.patient_id||null])).rows)}));
app.post('/api/v1/hospital/skin/treatments',run(async(req,res)=>{permission('specialty:skin:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for skin treatment creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_skin_treatments(tenant_id,patient_id,consultation_id,treatment_name,treatment_area,product_or_device,sessions_planned,notes,status) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *',[tid(req),b.patient_id,b.consultation_id||null,b.treatment_name,b.treatment_area||null,b.product_or_device||null,Number(b.sessions_planned)||1,b.notes||null,b.status||'planned']);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.patch('/api/v1/hospital/skin/treatments/:id',run(async(req,res)=>{permission('specialty:skin:write')(req);const b=req.body||{};const r=await q(req,"update hospital_skin_treatments set sessions_completed=coalesce($2,sessions_completed),status=coalesce($3,status),notes=coalesce($4,notes),completed_at=case when coalesce($3,status)='completed' then now() else completed_at end where id=$1 returning *",[param(req,'id'),b.sessions_completed==null?null:Number(b.sessions_completed),b.status,b.notes]);if(!r.rowCount)return json(res,{error:'Not found'},404);json(res,r.rows[0])}));

app.get('/api/v1/hospital/eecp/programs',run(async(req,res)=>{permission('specialty:eecp:read')(req);json(res,(await q(req,'select * from hospital_eecp_programs where patient_id=coalesce($1::uuid,patient_id) order by created_at desc limit 200',[req.query.patient_id||null])).rows)}));
app.post('/api/v1/hospital/eecp/programs',run(async(req,res)=>{permission('specialty:eecp:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for EECP program creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_eecp_programs(tenant_id,patient_id,cardiologist_user_id,indication,baseline_assessment,planned_sessions,treatment_notes,start_date) values($1,$2,$3,$4,$5,$6,$7,$8) returning *',[tid(req),b.patient_id,b.cardiologist_user_id||req.emtaf.userId,b.indication||null,b.baseline_assessment||null,Number(b.planned_sessions)||35,b.treatment_notes||null,b.start_date||null]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.patch('/api/v1/hospital/eecp/programs/:id',run(async(req,res)=>{permission('specialty:eecp:write')(req);const b=req.body||{};const r=await q(req,'update hospital_eecp_programs set sessions_completed=coalesce($2,sessions_completed),status=coalesce($3,status),treatment_notes=coalesce($4,treatment_notes),end_date=coalesce($5,end_date),updated_at=now() where id=$1 returning *',[param(req,'id'),b.sessions_completed==null?null:Number(b.sessions_completed),b.status,b.treatment_notes,b.end_date]);if(!r.rowCount)return json(res,{error:'Not found'},404);json(res,r.rows[0])}));
app.get('/api/v1/hospital/eecp/sessions',run(async(req,res)=>{permission('specialty:eecp:read')(req);json(res,(await q(req,'select * from hospital_eecp_sessions where patient_id=coalesce($1::uuid,patient_id) order by session_date desc nulls last,session_no desc limit 300',[req.query.patient_id||null])).rows)}));
app.post('/api/v1/hospital/eecp/sessions',run(async(req,res)=>{permission('specialty:eecp:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for EECP session creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_eecp_sessions(tenant_id,program_id,patient_id,session_no,therapist_user_id,duration_minutes,pre_systolic_bp,pre_diastolic_bp,pre_hr,post_systolic_bp,post_diastolic_bp,post_hr,tolerance,notes,status,session_date) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16) returning *',[tid(req),b.program_id,b.patient_id,Number(b.session_no),b.therapist_user_id||req.emtaf.userId,b.duration_minutes==null?null:Number(b.duration_minutes),b.pre_systolic_bp||null,b.pre_diastolic_bp||null,b.pre_hr==null?null:Number(b.pre_hr),b.post_systolic_bp||null,b.post_diastolic_bp||null,b.post_hr==null?null:Number(b.post_hr),b.tolerance||null,b.notes||null,b.status||'scheduled',b.session_date||null]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.patch('/api/v1/hospital/eecp/sessions/:id',run(async(req,res)=>{permission('specialty:eecp:write')(req);const b=req.body||{};const r=await q(req,'update hospital_eecp_sessions set status=coalesce($2,status),tolerance=coalesce($3,tolerance),notes=coalesce($4,notes),post_systolic_bp=coalesce($5,post_systolic_bp),post_diastolic_bp=coalesce($6,post_diastolic_bp),post_hr=coalesce($7,post_hr) where id=$1 returning *',[param(req,'id'),b.status,b.tolerance,b.notes,b.post_systolic_bp,b.post_diastolic_bp,b.post_hr==null?null:Number(b.post_hr)]);if(!r.rowCount)return json(res,{error:'Not found'},404);json(res,r.rows[0])}));

app.get('/api/v1/hospital/physio/assessments',run(async(req,res)=>{permission('specialty:physio:read')(req);json(res,(await q(req,'select * from hospital_physio_assessments where patient_id=coalesce($1::uuid,patient_id) order by created_at desc limit 200',[req.query.patient_id||null])).rows)}));
app.post('/api/v1/hospital/physio/assessments',run(async(req,res)=>{permission('specialty:physio:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for physio assessment creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_physio_assessments(tenant_id,patient_id,therapist_user_id,diagnosis,pain_score,mobility_findings,strength_findings,functional_goals,precautions,plan) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *',[tid(req),b.patient_id,b.therapist_user_id||req.emtaf.userId,b.diagnosis||null,b.pain_score==null?null:Number(b.pain_score),b.mobility_findings||null,b.strength_findings||null,b.functional_goals||null,b.precautions||null,b.plan||null]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.patch('/api/v1/hospital/physio/assessments/:id',run(async(req,res)=>{permission('specialty:physio:write')(req);const b=req.body||{};const r=await q(req,'update hospital_physio_assessments set pain_score=coalesce($2,pain_score),functional_goals=coalesce($3,functional_goals),precautions=coalesce($4,precautions),plan=coalesce($5,plan),status=coalesce($6,status),updated_at=now() where id=$1 returning *',[param(req,'id'),b.pain_score==null?null:Number(b.pain_score),b.functional_goals,b.precautions,b.plan,b.status]);if(!r.rowCount)return json(res,{error:'Not found'},404);json(res,r.rows[0])}));
app.get('/api/v1/hospital/physio/sessions',run(async(req,res)=>{permission('specialty:physio:read')(req);json(res,(await q(req,'select * from hospital_physio_sessions where patient_id=coalesce($1::uuid,patient_id) order by session_date desc nulls last,created_at desc limit 300',[req.query.patient_id||null])).rows)}));
app.post('/api/v1/hospital/physio/sessions',run(async(req,res)=>{permission('specialty:physio:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for physio session creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_physio_sessions(tenant_id,patient_id,assessment_id,therapist_user_id,session_date,session_type,exercises,modalities,pain_before,pain_after,response,home_program,status,notes) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) returning *',[tid(req),b.patient_id,b.assessment_id||null,b.therapist_user_id||req.emtaf.userId,b.session_date||null,b.session_type||null,b.exercises||null,b.modalities||null,b.pain_before==null?null:Number(b.pain_before),b.pain_after==null?null:Number(b.pain_after),b.response||null,b.home_program||null,b.status||'scheduled',b.notes||null]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.patch('/api/v1/hospital/physio/sessions/:id',run(async(req,res)=>{permission('specialty:physio:write')(req);const b=req.body||{};const r=await q(req,'update hospital_physio_sessions set status=coalesce($2,status),pain_after=coalesce($3,pain_after),response=coalesce($4,response),home_program=coalesce($5,home_program),notes=coalesce($6,notes) where id=$1 returning *',[param(req,'id'),b.status,b.pain_after==null?null:Number(b.pain_after),b.response,b.home_program,b.notes]);if(!r.rowCount)return json(res,{error:'Not found'},404);json(res,r.rows[0])}));
const specialty=(req:any)=>{const v=String(req.params.specialty||'');if(!['skin','eecp','physio'].includes(v))throw Object.assign(new Error('Unsupported specialty'),{statusCode:404});return v};
app.get('/api/v1/hospital/specialty/:specialty/dashboard',run(async(req,res)=>{const sp=specialty(req);permission(`specialty:${sp}:read`)(req);const [a,i]=await Promise.all([q(req,'select count(*)::int count from hospital_specialty_appointments where specialty=$1',[sp]),q(req,"select coalesce(sum(amount),0)::numeric total from hospital_specialty_invoices where specialty=$1 and status<>'paid'",[sp])]);json(res,{specialty:sp,appointments:a.rows[0].count,unpaidAmount:i.rows[0].total})}));
app.get('/api/v1/hospital/specialty/:specialty/appointments',run(async(req,res)=>{const sp=specialty(req);permission(`specialty:${sp}:read`)(req);json(res,(await q(req,'select * from hospital_specialty_appointments where specialty=$1 order by starts_at desc limit 300',[sp])).rows)}));
app.post('/api/v1/hospital/specialty/:specialty/appointments',run(async(req,res)=>{const sp=specialty(req);permission(`specialty:${sp}:write`)(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for specialty appointment creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_specialty_appointments(tenant_id,specialty,patient_id,provider_user_id,starts_at,ends_at,appointment_type,reason,notes) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *',[tid(req),sp,b.patient_id,b.provider_user_id||req.emtaf.userId,b.starts_at,b.ends_at||null,b.appointment_type||null,b.reason||null,b.notes||null]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.patch('/api/v1/hospital/specialty/:specialty/appointments/:id',run(async(req,res)=>{const sp=specialty(req);permission(`specialty:${sp}:write`)(req);const b=req.body||{};const r=await q(req,'update hospital_specialty_appointments set status=coalesce($2,status),notes=coalesce($3,notes),updated_at=now() where id=$1 and specialty=$4 returning *',[param(req,'id'),b.status,b.notes,sp]);if(!r.rowCount)return json(res,{error:'Not found'},404);json(res,r.rows[0])}));
app.get('/api/v1/hospital/specialty/:specialty/billing/packages',run(async(req,res)=>{const sp=specialty(req);permission(`specialty:${sp}:read`)(req);json(res,(await q(req,'select * from hospital_specialty_billing_packages where specialty=$1 and active=true order by name',[sp])).rows)}));
app.get('/api/v1/hospital/specialty/:specialty/billing/invoices',run(async(req,res)=>{const sp=specialty(req);permission(`specialty:${sp}:read`)(req);json(res,(await q(req,'select * from hospital_specialty_invoices where specialty=$1 order by issued_at desc limit 300',[sp])).rows)}));
app.post('/api/v1/hospital/specialty/:specialty/billing/invoices',run(async(req,res)=>{const sp=specialty(req);permission(`specialty:${sp}:billing`)(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for specialty invoice creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into hospital_specialty_invoices(tenant_id,specialty,patient_id,package_id,invoice_no,amount) values($1,$2,$3,$4,$5,$6) returning *',[tid(req),sp,b.patient_id,b.package_id||null,b.invoice_no,b.amount]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.get('/api/v1/hospital/specialty/:specialty/reports/summary',run(async(req,res)=>{const sp=specialty(req);permission(`specialty:${sp}:read`)(req);const a=await q(req,'select status,count(*)::int count from hospital_specialty_appointments where specialty=$1 group by status order by status',[sp]);const i=await q(req,'select status,count(*)::int count,coalesce(sum(amount),0)::numeric amount from hospital_specialty_invoices where specialty=$1 group by status order by status',[sp]);json(res,{specialty:sp,appointments:a.rows,invoices:i.rows})}));
app.get('/api/v1/hospital/specialty/:specialty/portal/me',run(async(req,res)=>{const sp=specialty(req);permission(`specialty:${sp}:read`)(req);const p=await q(req,"select id,mrn,first_name,last_name,dob,phone,email from hospital_patients where user_id=$1 and status='active' limit 1",[req.emtaf.userId]);if(!p.rowCount)return json(res,{error:'Patient profile not linked'},404);const patient=p.rows[0];const a=await q(req,'select * from hospital_specialty_appointments where specialty=$1 and patient_id=$2 order by starts_at desc',[sp,patient.id]);json(res,{patient,appointments:a.rows})}));
const port=Number(process.env.PORT||3000);const server=app.listen(port,()=>console.log(`hospital-service listening on ${port}`)); process.once('SIGTERM',()=>server.close()); process.once('SIGINT',()=>server.close());

