import { startTelemetry } from '@emtaf/core/dist/telemetry';
import express from 'express'; import cors from 'cors'; import rateLimit from 'express-rate-limit';
import helmet from 'helmet';
import client from 'prom-client';
import { db, audit, events, idempotent, getIdempotencyKey } from '@emtaf/core';
import { context, permission, error, json } from '@emtaf/core/dist/http';

startTelemetry(process.env.OTEL_SERVICE_NAME||'school-service');
const app = express(); app.disable('x-powered-by'); app.set('trust proxy', process.env.TRUST_PROXY||'1'); app.use(cors({origin:(process.env.CORS_ORIGINS||'').split(',').map((v:string)=>v.trim()).filter(Boolean),credentials:true})); app.use(rateLimit({windowMs:Number(process.env.RATE_LIMIT_WINDOW_MS||60000),limit:Number(process.env.RATE_LIMIT_MAX||300),standardHeaders:'draft-7',legacyHeaders:false,skip:(req:any)=>req.path.startsWith('/health')||req.path==='/metrics'}));
app.use(helmet({contentSecurityPolicy:process.env.NODE_ENV==='production'?undefined:false})); app.use(express.json({limit:'1mb'})); client.collectDefaultMetrics();
app.get('/health/live',(_,res)=>res.json({status:'ok',service:'school-service',version:process.env.SERVICE_VERSION||'1.10.5'}));
app.get('/health/ready',async(_,res)=>{try{await db.query('select 1');res.json({status:'ready'})}catch{res.status(503).json({status:'not-ready'})}});
app.get('/metrics',async(_,res)=>{res.setHeader('Content-Type',client.register.contentType);res.end(await client.register.metrics())});
app.use((req,res,next)=>{if(req.path.startsWith('/health')||req.path==='/metrics') return next(); context(req).then(()=>next()).catch(e=>error(res,e))});
const tenant=(req:any)=>req.emtaf.tenantId;
const run=(fn: import('express').RequestHandler): import('express').RequestHandler => (req,res,next)=>Promise.resolve().then(()=>fn(req,res,next)).catch(e=>error(res,e));
const q=(req:any,sql:string,values:any[]=[])=>db.withTenant(tenant(req),c=>c.query(sql,values)) as Promise<any>;

app.get('/api/v1/school/me',(req,res)=>json(res,{userId:req.emtaf.userId,tenantId:tenant(req),roles:req.emtaf.roles}));
app.get('/api/v1/school/dashboard',run(async(req,res)=>{permission('students:read')(req);const [s,c,a]=await Promise.all([q(req,"select count(*)::int count from school_students where status='active'"),q(req,"select count(*)::int count from school_classes where status='active'"),q(req,'select count(*)::int count from school_attendance where attendance_date=current_date')]);json(res,{students:s.rows[0].count,classes:c.rows[0].count,todaysAttendance:a.rows[0].count})}));

app.get('/api/v1/school/students',run(async(req,res)=>{permission('students:read')(req);const limit=Math.min(Number(req.query.limit)||50,200);const r=await q(req,'select * from school_students where status=\'active\' order by created_at desc limit $1',[limit]);json(res,r.rows)}));
app.post('/api/v1/school/students',run(async(req,res)=>{permission('students:write')(req);const b=req.body||{};if(!b.admission_no||!b.first_name||!b.last_name) return json(res,{error:'admission_no, first_name and last_name are required'},400);const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for student creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into school_students(tenant_id,admission_no,first_name,last_name,phone,email,user_id) values($1,$2,$3,$4,$5,$6,$7) returning *',[tenant(req),b.admission_no,b.first_name,b.last_name,b.phone||null,b.email||null,b.user_id||null]);await c.query('INSERT INTO platform_audit(tenant_id,user_id,action,entity,entity_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[tenant(req),req.emtaf.userId,'create','school_student',r.rows[0].id,{}]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.patch('/api/v1/school/students/:id',run(async(req,res)=>{permission('students:write')(req);const b=req.body||{};const r=await q(req,'update school_students set first_name=coalesce($2,first_name),last_name=coalesce($3,last_name),phone=coalesce($4,phone),email=coalesce($5,email),updated_at=now() where id=$1 and status=\'active\' returning *',[req.params.id,b.first_name,b.last_name,b.phone,b.email]);if(!r.rowCount)return json(res,{error:'Not found'},404);json(res,r.rows[0])}));
app.delete('/api/v1/school/students/:id',run(async(req,res)=>{permission('students:write')(req);const r=await q(req,"update school_students set status='deleted',updated_at=now() where id=$1 and status='active' returning id",[req.params.id]);if(!r.rowCount)return json(res,{error:'Not found'},404);json(res,{deleted:true})}));

app.get('/api/v1/school/teachers',run(async(req,res)=>{permission('students:read')(req);json(res,(await q(req,"select * from school_teachers where status='active' order by name")).rows)}));
app.post('/api/v1/school/teachers',run(async(req,res)=>{permission('students:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for teacher creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into school_teachers(tenant_id,user_id,employee_no,name) values($1,$2,$3,$4) returning *',[tenant(req),b.user_id,b.employee_no,b.name]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.get('/api/v1/school/classes',run(async(req,res)=>{permission('students:read')(req);json(res,(await q(req,"select * from school_classes where status='active' order by academic_year,name,section")).rows)}));
app.post('/api/v1/school/classes',run(async(req,res)=>{permission('students:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for class creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into school_classes(tenant_id,name,section,academic_year,class_teacher_id) values($1,$2,$3,$4,$5) returning *',[tenant(req),b.name,b.section,b.academic_year,b.class_teacher_id||null]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.post('/api/v1/school/enrollments',run(async(req,res)=>{permission('students:write')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for enrollment creation',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into school_enrollments(tenant_id,student_id,class_id) values($1,$2,$3) returning *',[tenant(req),b.student_id,b.class_id]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.post('/api/v1/school/attendance',run(async(req,res)=>{permission('attendance:manage')(req);const b=req.body||{};const key=getIdempotencyKey(req);if(!key)return json(res,{error:'Idempotency-Key header is required for attendance marking',requestId:req.emtaf.requestId},400);const result=await idempotent(req,key,async(c:any)=>{const r=await c.query('insert into school_attendance(tenant_id,student_id,class_id,attendance_date,status,marked_by) values($1,$2,$3,$4,$5,$6) on conflict(tenant_id,student_id,attendance_date) do update set status=excluded.status,class_id=excluded.class_id,marked_by=excluded.marked_by returning *',[tenant(req),b.student_id,b.class_id,b.attendance_date||new Date().toISOString().slice(0,10),b.status,req.emtaf.userId]);return {statusCode:201,body:r.rows[0]};});json(res,result.body,result.statusCode)}));
app.get('/api/v1/school/attendance',run(async(req,res)=>{permission('attendance:read')(req);const r=await q(req,'select * from school_attendance where attendance_date=coalesce($1::date,attendance_date) order by attendance_date desc limit 500',[req.query.date||null]);json(res,r.rows)}));

const port=Number(process.env.PORT||3000);const server=app.listen(port,()=>console.log(`school-service listening on ${port}`)); process.once('SIGTERM',()=>server.close()); process.once('SIGINT',()=>server.close());
