import express from 'express'; import helmet from 'helmet'; import client from 'prom-client'; import {db,audit} from '@emtaf/core'; import {context,roles,error,json} from '@emtaf/core/dist/http';
const app=express(); app.use(helmet()); app.use(express.json()); client.collectDefaultMetrics();
app.get('/health/live',(_,r)=>r.json({status:'ok',service:'tenant-service'})); app.get('/health/ready',async(_,r)=>{try{await db.query('select 1');r.json({status:'ready'})}catch{r.status(503).json({status:'not-ready'})}}); app.get('/metrics',async(_,r)=>{r.setHeader('Content-Type',client.register.contentType);r.end(await client.register.metrics())});
const protectedContext=(req:any,res:any,next:any)=>context(req).then(()=>next()).catch((e:any)=>error(res,e)); app.use(protectedContext);
app.get('/api/v1/tenants',async(req,res)=>{try{roles('superadmin')(req);const q=await db.query('select * from tenants order by created_at desc');json(res,q.rows)}catch(e){error(res,e)}});
app.post('/api/v1/tenants',async(req,res)=>{try{roles('superadmin')(req);const b=req.body;const q=await db.query('insert into tenants(code,name,domain) values($1,$2,$3) returning *',[b.code,b.name,b.domain||null]);json(res,q.rows[0],201)}catch(e){error(res,e)}});
app.post('/api/v1/tenants/:tenantId/memberships',async(req,res)=>{try{if(req.emtaf.tenantId!==req.params.tenantId) roles('superadmin')(req); else roles('superadmin','admin')(req);const b=req.body;const q=await db.query('insert into tenant_memberships(tenant_id,user_id,roles) values($1,$2,$3) on conflict(tenant_id,user_id) do update set roles=excluded.roles,status=\'active\' returning *',[req.params.tenantId,b.user_id,b.roles||[]]);await audit('membership.upsert',req.emtaf,'tenant_membership',`${req.params.tenantId}:${b.user_id}`,{roles:b.roles||[]});json(res,q.rows[0],201)}catch(e){error(res,e)}});
app.get('/api/v1/tenants/:tenantId/memberships',async(req,res)=>{try{if(req.emtaf.tenantId!==req.params.tenantId)roles('superadmin')(req);else roles('superadmin','admin')(req);const q=await db.query('select m.*,u.email,u.display_name from tenant_memberships m join users u on u.id=m.user_id where m.tenant_id=$1',[req.params.tenantId]);json(res,q.rows)}catch(e){error(res,e)}});
app.listen(Number(process.env.PORT||3000),()=>console.log('tenant-service listening'));
