import type { AuthContext } from './index';

export const rolePermissions:Record<string,string[]>={
    superadmin:['*'], admin:['tenant:read','tenant:write','users:manage','patients:read','patients:write','clinical:read','clinical:write','appointments:manage','billing:read','billing:write','departments:read','departments:write','staff:read','staff:write','beds:read','beds:write','admissions:read','admissions:write','prescriptions:read','prescriptions:write','lab:read','lab:write','radiology:read','radiology:write','insurance:read','insurance:write','discharge:write','students:read','students:write','guests:read','guests:write','rooms:manage','attendance:manage','attendance:read','college:read','college:write','faculty:manage','courses:manage','enrollments:manage','fees:manage','exams:manage','properties:read','properties:write','units:manage','listings:manage','leads:manage','viewings:manage','leases:manage','payments:manage','realestate:reports','rooms:read','rooms:manage','bookings:manage','checkin:manage','housekeeping:manage','hotel:reports'],
    doctor:['patients:read','patients:write','clinical:read','clinical:write','appointments:manage','departments:read','staff:read','prescriptions:read','prescriptions:write','lab:read','lab:write','radiology:read','radiology:write','admissions:read','admissions:write','discharge:write','billing:read','insurance:read','insurance:write'], nurse:['patients:read','clinical:read','clinical:write','appointments:read','departments:read','staff:read','admissions:read','admissions:write','beds:read','beds:write','prescriptions:read','lab:read','lab:write','radiology:read'],
    accountant:['patients:read','billing:read','billing:write','insurance:read','insurance:write'], receptionist:['patients:read','patients:write','appointments:manage','departments:read','admissions:read','admissions:write','beds:read'], patient:['patients:self','appointments:self','clinical:self','billing:self','prescriptions:self','lab:self','radiology:self'], teacher:['students:read','students:write','attendance:manage','attendance:read'], student:['students:self','attendance:self'], parent:['students:self','attendance:self'], faculty:['college:read','college:write','faculty:read','courses:read','enrollments:read','attendance:manage','attendance:read','exams:manage'], manager:['guests:read','guests:write','rooms:manage','rooms:read','bookings:manage','checkin:manage','housekeeping:manage','hotel:reports'], hoteladmin:['guests:read','guests:write','rooms:manage','rooms:read','bookings:manage','checkin:manage','housekeeping:manage','hotel:reports','billing:write'], housekeeping:['guests:read','rooms:read','rooms:manage','housekeeping:manage'], guest:['guests:self','bookings:self'], hotel_guest:['guests:self','bookings:self'], guests:['guests:read','guests:write'], collegeadmin:['college:read','college:write','faculty:manage','faculty:read','courses:manage','courses:read','enrollments:manage','attendance:manage','attendance:read','fees:manage','exams:manage'], college_student:['college:self','courses:self','attendance:self','fees:self','exams:self'], realestateadmin:['properties:read','properties:write','units:manage','listings:manage','leads:manage','viewings:manage','leases:manage','payments:manage','realestate:reports'], agent:['properties:read','listings:manage','leads:manage','viewings:manage','leases:read'], property_manager:['properties:read','units:manage','leases:manage','payments:manage','viewings:manage'], realestate_accountant:['properties:read','leases:read','payments:manage','realestate:reports'], buyer:['properties:read','listings:read','viewings:self','offers:self'], tenant:['properties:read','leases:self','payments:self','maintenance:self'], students:['students:read','students:write']
};

export function requireRoles(ctx:AuthContext,allowed:string[]){
  if(!allowed.some(r=>ctx.roles.includes(r))) throw Object.assign(new Error('Forbidden'),{statusCode:403});
}
export function requirePermission(ctx:AuthContext,permission:string){
  if(!ctx.roles.some(r=>rolePermissions[r]?.includes('*')||rolePermissions[r]?.includes(permission))) throw Object.assign(new Error('Forbidden'),{statusCode:403});
}
export function hasPermission(role:string,permission:string){
  return rolePermissions[role]?.includes('*')||rolePermissions[role]?.includes(permission)||false;
}
