image:
  repository: emtaf-realestate-service
  tag: dev
imagePullPolicy: IfNotPresent
replicaCount: 2
namespace: emtaf
service:
  port: 80
resources:
  requests: {cpu: 100m, memory: 128Mi}
  limits: {cpu: 500m, memory: 512Mi}
hpa: {minReplicas: 2, maxReplicas: 10, cpu: 70, memory: 75}
envFromSecret: emtaf-platform-secrets
envFromConfig: emtaf-platform-config
