(() => {
  'use strict';
  const tenants = [
    {id:'hospital',name:'Demo City Hospital',domain:'Hospital',roles:['superadmin','admin','doctor','nurse','accountant','receptionist','patient']},
    {id:'school',name:'Demo Public School',domain:'School',roles:['superadmin','admin','teacher','parent','student']},
    {id:'college',name:'Demo Institute of Technology',domain:'College',roles:['superadmin','admin','faculty','student']},
    {id:'hotel',name:'Demo Grand Hotel',domain:'Hotel',roles:['superadmin','admin','frontdesk','guest']},
    {id:'realestate',name:'Demo Realty Group',domain:'Real Estate',roles:['superadmin','realestateadmin','agent','buyer']}
  ];
  const icons = {dashboard:'⌂',patients:'♙',staff:'◉',appointments:'◷',billing:'₹',students:'♙',classes:'▦',attendance:'✓',faculty:'◉',courses:'▤',rooms:'▦',bookings:'▣',properties:'⌂',listings:'◇',leads:'◌',settings:'⚙'};
  const data = {
    hospital:{metrics:[['Patients','1,284','+8.4%'],['Appointments','96','+12 today'],['Admissions','42','6 new'],['Unpaid billing','₹4.8L','18 invoices']],table:['MRN','Patient','Doctor','Status'],rows:[['MRN-1001','Rahul Verma','Dr. Ananya Sharma','Active'],['MRN-1002','Sunita Rao','Dr. Vikram Shah','Admitted'],['MRN-1003','Amit Joshi','Dr. Neha Iyer','Discharged'],['MRN-1004','Kavita Singh','Dr. Ananya Sharma','Active']]},
    school:{metrics:[['Students','842','+3.2%'],['Classes','28','4 active now'],['Attendance','94.2%','Today'],['Pending fees','₹2.1L','37 accounts']],table:['Admission','Student','Class','Attendance'],rows:[['ADM-1001','Aarav Sharma','Grade 8-A','Present'],['ADM-1002','Ananya Patel','Grade 9-B','Present'],['ADM-1003','Kabir Singh','Grade 8-A','Late'],['ADM-1004','Diya Mehta','Grade 10-A','Absent']]},
    college:{metrics:[['Students','4,820','+5.1%'],['Faculty','214','12 departments'],['Courses','186','32 this term'],['Enrollments','12,480','Fall 2026']],table:['Enrollment','Student','Course','Status'],rows:[['STU-1001','Ishita Mehta','CSE101','Active'],['STU-1002','Arjun Rao','ECE204','Active'],['STU-1003','Nisha Jain','MTH110','Active'],['STU-1004','Rohan Das','CSE305','Pending']]},
    hotel:{metrics:[['Occupancy','78%','+6.3%'],['Bookings','126','24 today'],['Available rooms','31','of 142'],['Revenue','₹18.6L','This month']],table:['Booking','Guest','Room','Status'],rows:[['BKG-1001','Rohan Gupta','301','Booked'],['BKG-1002','Meera Kapoor','512','Checked in'],['BKG-1003','Vivek Shah','204','Reserved'],['BKG-1004','Sara Khan','610','Checked out']]},
    realestate:{metrics:[['Properties','148','12 new'],['Listings','324','+18 this week'],['Leads','86','21 hot'],['Pipeline','₹42.8Cr','Active offers']],table:['Property','Unit','Listing','Price'],rows:[['PROP-1001','A-301','3 BHK Lakeview','₹87.5L'],['PROP-1002','B-1204','2 BHK Central','₹64.0L'],['PROP-1003','V-08','Villa — East Park','₹1.84Cr'],['PROP-1004','O-210','Office — CBD','₹1.12Cr']]}
  };
  let current = 'hospital'; let currentPage='Dashboard'; let currentRole='superadmin';
  const tenantSelect=document.getElementById('tenantSelect'), nav=document.getElementById('nav'), view=document.getElementById('view');
  tenants.forEach(t=>{const o=document.createElement('option');o.value=t.id;o.textContent=t.name;tenantSelect.appendChild(o);});
  function tenant(){return tenants.find(t=>t.id===current)}
  function menu(){
    const maps={hospital:[['dashboard','Dashboard'],['patients','Patients'],['staff','Staff'],['appointments','Appointments'],['billing','Billing']],school:[['dashboard','Dashboard'],['students','Students'],['classes','Classes'],['attendance','Attendance']],college:[['dashboard','Dashboard'],['students','Students'],['faculty','Faculty'],['courses','Courses'],['attendance','Attendance']],hotel:[['dashboard','Dashboard'],['rooms','Rooms'],['bookings','Bookings'],['billing','Payments']],realestate:[['dashboard','Dashboard'],['properties','Properties'],['listings','Listings'],['leads','Leads'],['billing','Leases & Payments']]};
    nav.innerHTML=maps[current].map(([id,label])=>`<button class="${currentPage===label?'active':''}" data-page="${label}"><span class="nav-icon">${icons[id]||'•'}</span>${label}</button>`).join('');
    nav.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{currentPage=b.dataset.page;render();}));
  }
  function badge(v){const x=v.toLowerCase();const cls=x.includes('active')||x.includes('present')||x.includes('booked')||x.includes('checked in')?'success':x.includes('pending')||x.includes('late')||x.includes('reserved')?'warn':x.includes('absent')||x.includes('unpaid')?'danger':'info';return `<span class="badge ${cls}">${v}</span>`;}
  function dashboard(){const d=data[current]; return `<div class="page-head"><div><h1>${tenant().domain} Dashboard</h1><p>Tenant-isolated operational view for <strong>${tenant().name}</strong>.</p></div><div class="actions"><button class="btn" onclick="window.demoToast('Export queued')">Export</button><button class="btn primary" onclick="window.demoToast('Create workflow opened')">+ New</button></div></div>
    <div class="grid metrics">${d.metrics.map(m=>`<div class="card metric"><div class="label">${m[0]}</div><div class="value">${m[1]}</div><div class="delta">${m[2]}</div></div>`).join('')}</div>
    <div class="grid two"><div class="card"><div class="card-head"><h3>Activity trend</h3><span class="badge info">Last 7 days</span></div><div class="card-body"><div class="bars">${[42,58,49,74,63,88,71,95,80,91].map((n,i)=>`<div class="bar" style="height:${n}%"><span>${n}</span></div>`).join('')}</div><div class="axis"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></div>
    <div class="card"><div class="card-head"><h3>Recent activity</h3><span class="badge success">Live</span></div><div class="card-body"><div class="activity">${['New record created','Workflow approved','Payment received','User membership updated'].map((x,i)=>`<div class="activity-item"><span class="activity-dot"></span><div><strong>${x}</strong><small>${i+2} minutes ago · ${tenant().name}</small></div></div>`).join('')}</div></div></div></div>
    <div class="card" style="margin-top:16px"><div class="card-head"><h3>Operational queue</h3><button class="btn" onclick="window.demoToast('Opening queue')">View all</button></div><div class="table-wrap"><table class="table"><thead><tr>${d.table.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${d.rows.map(r=>`<tr>${r.map((c,i)=>`<td>${i===r.length-1?badge(c):c}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div>`;}
  function resourcePage(){const names={hospital:{Patients:['MRN-1001','Rahul Verma','Male','Active'],school:{Students:['ADM-1001','Aarav Sharma','Grade 8-A','Present']},college:{Students:['STU-1001','Ishita Mehta','CSE101','Active']},hotel:{Rooms:['301','Deluxe','3rd Floor','Available']},realestate:{Properties:['PROP-1001','Lakeview Residency','Residential','Active']}}}; const d=data[current]; let title=currentPage; let rows=d.rows.map((r,i)=>r); return `<div class="page-head"><div><h1>${title}</h1><p>${tenant().name} · tenant-scoped records and RBAC controlled actions.</p></div><div class="actions"><input class="search" placeholder="Search ${title.toLowerCase()}…"><button class="btn primary" onclick="window.demoToast('Create ${title.slice(0,-1)||title} opened')">+ Create</button></div></div><div class="card"><div class="card-head"><h3>${title} registry</h3><div class="role-box">${tenant().roles.map(r=>`<button class="role ${r===currentRole?'selected':''}" data-role="${r}">${r}</button>`).join('')}</div></div><div class="table-wrap"><table class="table"><thead><tr>${d.table.map(h=>`<th>${h}</th>`).join('')}<th>Actions</th></tr></thead><tbody>${rows.concat(rows).slice(0,6).map((r,i)=>`<tr>${r.map((c,j)=>`<td>${j===r.length-1?badge(c):c}</td>`).join('')}<td><button class="btn" onclick="window.demoToast('Opening record ${i+1}')">Open</button></td></tr>`).join('')}</tbody></table></div></div>`;}
  function render(){document.getElementById('tenantDomain').textContent=tenant().domain;document.getElementById('pageTitle').textContent=currentPage;document.getElementById('roleLabel').textContent=currentRole;menu();view.innerHTML=currentPage==='Dashboard'?dashboard():resourcePage();view.querySelectorAll('.role').forEach(b=>b.addEventListener('click',()=>{currentRole=b.dataset.role;render();window.demoToast('Role switched to '+currentRole);}));}
  window.demoToast=(message)=>{const t=document.getElementById('toast');t.textContent=message;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1800)};
  tenantSelect.addEventListener('change',()=>{current=tenantSelect.value;currentPage='Dashboard';currentRole=tenant().roles[0];render();window.demoToast('Switched to '+tenant().name)});
  document.getElementById('menuButton').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));
  render();
})();
