apiVersion: apps/v1
kind: Deployment
metadata: {name: school-service}
spec:
 template:
  spec:
   containers:
   - name: school-service
     envFrom:
     - configMapRef: {name: external-platform-config}
     - secretRef: {name: emtaf-platform-secrets}
