apiVersion: apps/v1
kind: Deployment
metadata: {name: emtaf-outbox-worker}
spec:
 template:
  spec:
   containers:
   - name: worker
     envFrom:
     - configMapRef: {name: external-platform-config}
     - secretRef: {name: emtaf-platform-secrets}
