apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: emtaf
resources:
- ../../base
- external-config.yaml
- external-secrets.yaml
- external-egress.yaml
images:
- name: emtaf-tenant-service
  newName: REGISTRY/emtaf-tenant-service
  newTag: IMAGE_TAG
- name: emtaf-hospital-service
  newName: REGISTRY/emtaf-hospital-service
  newTag: IMAGE_TAG
- name: emtaf-school-service
  newName: REGISTRY/emtaf-school-service
  newTag: IMAGE_TAG
- name: emtaf-college-service
  newName: REGISTRY/emtaf-college-service
  newTag: IMAGE_TAG
- name: emtaf-hotel-service
  newName: REGISTRY/emtaf-hotel-service
  newTag: IMAGE_TAG
- name: emtaf-realestate-service
  newName: REGISTRY/emtaf-realestate-service
  newTag: IMAGE_TAG
- name: emtaf-migrations
  newName: REGISTRY/emtaf-migrations
  newTag: IMAGE_TAG

patches:
- path: remove-deployment-postgres.yaml
- path: remove-deployment-redis.yaml
- path: remove-deployment-redpanda.yaml
- path: remove-service-postgres.yaml
- path: remove-service-redis.yaml
- path: remove-service-redpanda.yaml
- path: remove-secret-postgres-secret.yaml
- path: remove-deployment-emtaf-demo-wireframe.yaml
- path: remove-service-emtaf-demo-wireframe.yaml
- path: drop-demo-from-ingress-policy.yaml
- path: hospital-service-env-patch.yaml
- path: school-service-env-patch.yaml
- path: college-service-env-patch.yaml
- path: hotel-service-env-patch.yaml
- path: realestate-service-env-patch.yaml
- path: tenant-env-patch.yaml
- path: worker-env-patch.yaml
- path: migration-env-patch.yaml
