apiVersion: apps/v1
kind: Deployment
metadata: {name: postgres}
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: redis}
$patch: delete
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: redpanda}
$patch: delete
---
apiVersion: v1
kind: Service
metadata: {name: postgres}
$patch: delete
---
apiVersion: v1
kind: Service
metadata: {name: redis}
$patch: delete
---
apiVersion: v1
kind: Service
metadata: {name: redpanda}
$patch: delete
---
apiVersion: v1
kind: Secret
metadata: {name: postgres-secret}
$patch: delete
